const widthArray = [
  { title: "1" },
  { title: "1.2" },
  { title: "1.4" },
  { title: "1.6" },
  { title: "1.8" },
  { title: "2" },
  { title: "2.5" },
  { title: "3" },
  { title: "3.5" },
  { title: "4" },
  { title: "5" },
  { title: "5.5" },
  { title: "6" },
  { title: "7" },
  { title: "8" },
  { title: "10" },
  { title: "12" },
  { title: "14" },
  { title: "16" },
  { title: "18" },
  { title: "20" },
  { title: "22" },
  { title: "24" },
  { title: "27" },
  { title: "30" },
];

export default widthArray;
